// react-app/src/scripts/views/guide/index.js
import React, { Component } from 'react';
import { connect } from "react-redux"
import { Carousel, WingBlank } from 'antd-mobile';
@connect(
    state => {
        console.log(state.data);
        return {
            data: state.data
        }
    }
)
class Guide extends Component {
    componentWillMount() {
        if (localStorage.guideCount) {
            localStorage.guideCount++;
            if (localStorage.guideCount > 3) {
                const { history } = this.props;
                history.push("/app/home")
            }
        } else {
            localStorage.guideCount = 1;
        }
    }
    goHome = (index) => {
        if (index === this.props.data.guides.length - 1) {
            const { history } = this.props;
            history.push("/app/home")
        }
    }
    render() {
        console.log(this.props.data)
        const {
            data: {
                guides
            }
        } = this.props;
        return (
            <div >
                <WingBlank>
                    <Carousel
                        autoplay={false}
                        dots={true}
                    >
                        {guides.map((item, i) => (
                            <div key={i} className="box">
                                <img
                                    src={item}
                                    alt=""
                                    style={{ width: '100%', height: "100%" }}
                                    onClick={() => this.goHome(i)}
                                />
                            </div>
                        ))}
                    </Carousel>
                </WingBlank>
            </div>
        )
    }
}
export default Guide;

// 王行建/src/views/guide.vue
<template>
  <div>
    <van-swipe :autoplay="0" indicator-color="white">
      <van-swipe-item v-for="(img,i) in imgs" :key="i">
        <img :src="img" alt class="swiper" @click="gotoHome(i)">
      </van-swipe-item>
    </van-swipe>
  </div>
</template>
<script>
export default {
  name: "guide",
  data() {
    return {
      imgs: [
        require("@/assets/images/slide1.png"),
        require("@/assets/images/slide2.png"),
        require("@/assets/images/slide3.png"),
        require("@/assets/images/slide4.png")
      ]
    };
  },
  methods: {
    gotoHome(i) {
      if (i == this.imgs.length - 1) {
        this.$router.push({ name: "home" });
      }
    }
  },
  mounted() {
    if (localStorage.count) {
      localStorage.count++;
      if (localStorage.count > 2) {
        this.$router.push({ name: "home" });
      }
    } else {
      localStorage.count = 1;
    }
  }
};
</script>

<style scoped>
.guide .swiper {
  width: 100%;
  height: 100%;
}
</style>
